artifact_uri: 1/1/23d60a212bad4888bbf17afa4a30c8f4/artifacts
end_time: 1652735871750
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 23d60a212bad4888bbf17afa4a30c8f4
run_uuid: 23d60a212bad4888bbf17afa4a30c8f4
source_name: ''
source_type: 4
source_version: ''
start_time: 1652735870578
status: 4
tags: []
user_id: utkusaglam
