channels:
- conda-forge
dependencies:
- python=3.9.10
- pip<=21.2.4
- pip:
  - mlflow
  - cloudpickle==2.0.0
  - psutil==5.9.0
  - scikit-learn==1.1.0
  - typing-extensions==4.2.0
  - typing==3.7.4.3
name: mlflow-env
